const  {prisma}  = require("@prisma/client");

async function seedContributionTypes() {
  const moreMembers = [
    {
      custom_id: "M-0006",
      first_name: "Sahle",
      second_name: "Worku",
      last_name: "Fikru",
      profession: "Engineer",
      title: "Mr.",
      job_business: "Construction",
      id_number: "ETID1006",
      birth_date: new Date("1988-11-05"),
      citizen: "Ethiopian",
      joined_date: new Date("2022-02-15"),
      wereda: "06",
      zone_or_district: "Yeka",
      kebele: "04",
      sex: "MALE",
      phone_number: "0911765432",
      phone_number_2: "0922765432",
      member_type: "REGULAR",
      bank_name: "Dashen Bank",
      bank_account_number: "100000000006",
      bank_account_name: "Sahle Worku",
      email: "sahle6@example.com",
      email_2: "sahle6alt@example.com",
      image_url: "https://example.com/images/sahle.jpg",
      image_file_id: "img_006",
      document: "https://example.com/docs/sahle.pdf",
      document_file_id: "doc_006",
      remark: "Reliable",
      status: "ACTIVE",
    },
    {
      custom_id: "M-0007",
      first_name: "Mulu",
      second_name: "Tadesse",
      last_name: "Kebede",
      profession: "Pharmacist",
      title: "Ms.",
      job_business: "Pharmacy",
      id_number: "ETID1007",
      birth_date: new Date("1993-01-22"),
      citizen: "Ethiopian",
      joined_date: new Date("2021-07-10"),
      wereda: "09",
      zone_or_district: "Kolfe Keranio",
      kebele: "08",
      sex: "FEMALE",
      phone_number: "0911876543",
      phone_number_2: "0922876543",
      member_type: "ASSOCIATE",
      bank_name: "Nib Bank",
      bank_account_number: "100000000007",
      bank_account_name: "Mulu Tadesse",
      email: "mulu7@example.com",
      email_2: "mulu7alt@example.com",
      image_url: "https://example.com/images/mulu.jpg",
      image_file_id: "img_007",
      document: "https://example.com/docs/mulu.pdf",
      document_file_id: "doc_007",
      remark: "Part-time member",
      status: "ACTIVE",
    },
    {
      custom_id: "M-0008",
      first_name: "Tesfaye",
      second_name: "Bekele",
      last_name: "Hailemariam",
      profession: "Farmer",
      title: "Mr.",
      job_business: "Agriculture",
      id_number: "ETID1008",
      birth_date: new Date("1975-08-30"),
      citizen: "Ethiopian",
      joined_date: new Date("2019-11-20"),
      wereda: "12",
      zone_or_district: "Akaki Kality",
      kebele: "15",
      sex: "MALE",
      phone_number: "0911654321",
      phone_number_2: "0922654321",
      member_type: "SUPPORTING",
      bank_name: "Awash Bank",
      bank_account_number: "100000000008",
      bank_account_name: "Tesfaye Bekele",
      email: "tesfaye8@example.com",
      email_2: "tesfaye8alt@example.com",
      image_url: "https://example.com/images/tesfaye.jpg",
      image_file_id: "img_008",
      document: "https://example.com/docs/tesfaye.pdf",
      document_file_id: "doc_008",
      remark: "Supports community",
      status: "INACTIVE",
    },
    {
      custom_id: "M-0009",
      first_name: "Eyerusalem",
      second_name: "Alemu",
      last_name: "Gebremichael",
      profession: "Lawyer",
      title: "Mrs.",
      job_business: "Legal Firm",
      id_number: "ETID1009",
      birth_date: new Date("1984-04-13"),
      citizen: "Ethiopian",
      joined_date: new Date("2020-01-05"),
      wereda: "02",
      zone_or_district: "Lideta",
      kebele: "03",
      sex: "FEMALE",
      phone_number: "0911345679",
      phone_number_2: "0922345679",
      member_type: "REGULAR",
      bank_name: "CBE",
      bank_account_number: "100000000009",
      bank_account_name: "Eyerusalem Alemu",
      email: "eyerusalem9@example.com",
      email_2: "eyerusalem9alt@example.com",
      image_url: "https://example.com/images/eyerusalem.jpg",
      image_file_id: "img_009",
      document: "https://example.com/docs/eyerusalem.pdf",
      document_file_id: "doc_009",
      remark: "Active in meetings",
      status: "ACTIVE",
    },
    {
      custom_id: "M-0010",
      first_name: "Getachew",
      second_name: "Mamo",
      last_name: "Abebe",
      profession: "Merchant",
      title: "Mr.",
      job_business: "Trading",
      id_number: "ETID1010",
      birth_date: new Date("1978-12-22"),
      citizen: "Ethiopian",
      joined_date: new Date("2018-05-18"),
      wereda: "08",
      zone_or_district: "Arada",
      kebele: "07",
      sex: "MALE",
      phone_number: "0911122334",
      phone_number_2: "0922122334",
      member_type: "ASSOCIATE",
      bank_name: "Nib Bank",
      bank_account_number: "100000000010",
      bank_account_name: "Getachew Mamo",
      email: "getachew10@example.com",
      email_2: "getachew10alt@example.com",
      image_url: "https://example.com/images/getachew.jpg",
      image_file_id: "img_010",
      document: "https://example.com/docs/getachew.pdf",
      document_file_id: "doc_010",
      remark: "Good standing",
      status: "ACTIVE",
    },
    {
      custom_id: "M-0011",
      first_name: "Hirut",
      second_name: "Fikadu",
      last_name: "Mekonnen",
      profession: "PhD Student",
      title: "Ms.",
      job_business: "University",
      id_number: "ETID1011",
      birth_date: new Date("1995-09-09"),
      citizen: "Ethiopian",
      joined_date: new Date("2023-03-10"),
      wereda: "01",
      zone_or_district: "Addis Ketema",
      kebele: "11",
      sex: "FEMALE",
      phone_number: "0911987654",
      phone_number_2: "0922987654",
      member_type: "REGULAR",
      bank_name: "Dashen Bank",
      bank_account_number: "100000000011",
      bank_account_name: "Hirut Fikadu",
      email: "hirut11@example.com",
      email_2: "hirut11alt@example.com",
      image_url: "https://example.com/images/hirut.jpg",
      image_file_id: "img_011",
      document: "https://example.com/docs/hirut.pdf",
      document_file_id: "doc_011",
      remark: "Active in social events",
      status: "ACTIVE",
    },
    {
      custom_id: "M-0012",
      first_name: "Dawit",
      second_name: "Gebremedhin",
      last_name: "Yosef",
      profession: "Photographer",
      title: "Mr.",
      job_business: "Media",
      id_number: "ETID1012",
      birth_date: new Date("1983-07-30"),
      citizen: "Ethiopian",
      joined_date: new Date("2021-06-25"),
      wereda: "04",
      zone_or_district: "Gulele",
      kebele: "06",
      sex: "MALE",
      phone_number: "0911348765",
      phone_number_2: "0922348765",
      member_type: "SUPPORTING",
      bank_name: "Awash Bank",
      bank_account_number: "100000000012",
      bank_account_name: "Dawit Gebremedhin",
      email: "dawit12@example.com",
      email_2: "dawit12alt@example.com",
      image_url: "https://example.com/images/dawit.jpg",
      image_file_id: "img_012",
      document: "https://example.com/docs/dawit.pdf",
      document_file_id: "doc_012",
      remark: "Supports photography events",
      status: "ACTIVE",
    },
    {
      custom_id: "M-0013",
      first_name: "Selam",
      second_name: "Mekonnen",
      last_name: "Fikadu",
      profession: "Chef",
      title: "Ms.",
      job_business: "Restaurant",
      id_number: "ETID1013",
      birth_date: new Date("1991-10-11"),
      citizen: "Ethiopian",
      joined_date: new Date("2020-09-14"),
      wereda: "03",
      zone_or_district: "Lideta",
      kebele: "02",
      sex: "FEMALE",
      phone_number: "0911223344",
      phone_number_2: "0922223344",
      member_type: "REGULAR",
      bank_name: "CBE",
      bank_account_number: "100000000013",
      bank_account_name: "Selam Mekonnen",
      email: "selam13@example.com",
      email_2: "selam13alt@example.com",
      image_url: "https://example.com/images/selam.jpg",
      image_file_id: "img_013",
      document: "https://example.com/docs/selam.pdf",
      document_file_id: "doc_013",
      remark: "Catering specialist",
      status: "ACTIVE",
    },
    {
      custom_id: "M-0014",
      first_name: "Birhanu",
      second_name: "Tadesse",
      last_name: "Admasu",
      profession: "Carpenter",
      title: "Mr.",
      job_business: "Construction",
      id_number: "ETID1014",
      birth_date: new Date("1980-01-25"),
      citizen: "Ethiopian",
      joined_date: new Date("2019-04-30"),
      wereda: "05",
      zone_or_district: "Kirkos",
      kebele: "08",
      sex: "MALE",
      phone_number: "0911987765",
      phone_number_2: "0922987765",
      member_type: "SUPPORTING",
      bank_name: "Dashen Bank",
      bank_account_number: "100000000014",
      bank_account_name: "Birhanu Tadesse",
      email: "birhanu14@example.com",
      email_2: "birhanu14alt@example.com",
      image_url: "https://example.com/images/birhanu.jpg",
      image_file_id: "img_014",
      document: "https://example.com/docs/birhanu.pdf",
      document_file_id: "doc_014",
      remark: "Supports events",
      status: "ACTIVE",
    },
    {
      custom_id: "M-0015",
      first_name: "Hanna",
      second_name: "Mekonnen",
      last_name: "Tesfaye",
      profession: "Dentist",
      title: "Dr.",
      job_business: "Clinic",
      id_number: "ETID1015",
      birth_date: new Date("1989-03-19"),
      citizen: "Ethiopian",
      joined_date: new Date("2021-08-22"),
      wereda: "07",
      zone_or_district: "Lideta",
      kebele: "03",
      sex: "FEMALE",
      phone_number: "0911776655",
      phone_number_2: "0922776655",
      member_type: "REGULAR",
      bank_name: "Awash Bank",
      bank_account_number: "100000000015",
      bank_account_name: "Hanna Mekonnen",
      email: "hanna15@example.com",
      email_2: "hanna15alt@example.com",
      image_url: "https://example.com/images/hanna.jpg",
      image_file_id: "img_015",
      document: "https://example.com/docs/hanna.pdf",
      document_file_id: "doc_015",
      remark: "Health professional",
      status: "ACTIVE",
    },
    {
      custom_id: "M-0016",
      first_name: "Solomon",
      second_name: "Haile",
      last_name: "Tadesse",
      profession: "IT Specialist",
      title: "Mr.",
      job_business: "Tech Firm",
      id_number: "ETID1016",
      birth_date: new Date("1986-12-04"),
      citizen: "Ethiopian",
      joined_date: new Date("2020-11-13"),
      wereda: "02",
      zone_or_district: "Arada",
      kebele: "06",
      sex: "MALE",
      phone_number: "0911445566",
      phone_number_2: "0922445566",
      member_type: "ASSOCIATE",
      bank_name: "CBE",
      bank_account_number: "100000000016",
      bank_account_name: "Solomon Haile",
      email: "solomon16@example.com",
      email_2: "solomon16alt@example.com",
      image_url: "https://example.com/images/solomon.jpg",
      image_file_id: "img_016",
      document: "https://example.com/docs/solomon.pdf",
      document_file_id: "doc_016",
      remark: "Tech support",
      status: "ACTIVE",
    },
    {
      custom_id: "M-0017",
      first_name: "Meriem",
      second_name: "Gebremichael",
      last_name: "Tesfaye",
      profession: "Journalist",
      title: "Ms.",
      job_business: "Media",
      id_number: "ETID1017",
      birth_date: new Date("1994-06-17"),
      citizen: "Ethiopian",
      joined_date: new Date("2023-02-25"),
      wereda: "09",
      zone_or_district: "Kolfe Keranio",
      kebele: "01",
      sex: "FEMALE",
      phone_number: "0911334455",
      phone_number_2: "0922334455",
      member_type: "REGULAR",
      bank_name: "Nib Bank",
      bank_account_number: "100000000017",
      bank_account_name: "Meriem Gebremichael",
      email: "meriem17@example.com",
      email_2: "meriem17alt@example.com",
      image_url: "https://example.com/images/meriem.jpg",
      image_file_id: "img_017",
      document: "https://example.com/docs/meriem.pdf",
      document_file_id: "doc_017",
      remark: "Writes for newsletter",
      status: "ACTIVE",
    },
    {
      custom_id: "M-0018",
      first_name: "Biruk",
      second_name: "Abebe",
      last_name: "Yohannes",
      profession: "Mechanic",
      title: "Mr.",
      job_business: "Auto Shop",
      id_number: "ETID1018",
      birth_date: new Date("1982-07-29"),
      citizen: "Ethiopian",
      joined_date: new Date("2019-03-04"),
      wereda: "11",
      zone_or_district: "Akaki Kality",
      kebele: "10",
      sex: "MALE",
      phone_number: "0911556677",
      phone_number_2: "0922556677",
      member_type: "SUPPORTING",
      bank_name: "Awash Bank",
      bank_account_number: "100000000018",
      bank_account_name: "Biruk Abebe",
      email: "biruk18@example.com",
      email_2: "biruk18alt@example.com",
      image_url: "https://example.com/images/biruk.jpg",
      image_file_id: "img_018",
      document: "https://example.com/docs/biruk.pdf",
      document_file_id: "doc_018",
      remark: "Helpful member",
      status: "ACTIVE",
    },
    {
      custom_id: "M-0019",
      first_name: "Fikirte",
      second_name: "Tesfaye",
      last_name: "Kebede",
      profession: "Teacher",
      title: "Ms.",
      job_business: "High School",
      id_number: "ETID1019",
      birth_date: new Date("1990-08-23"),
      citizen: "Ethiopian",
      joined_date: new Date("2022-12-01"),
      wereda: "10",
      zone_or_district: "Nifas Silk",
      kebele: "14",
      sex: "FEMALE",
      phone_number: "0911667788",
      phone_number_2: "0922667788",
      member_type: "REGULAR",
      bank_name: "Dashen Bank",
      bank_account_number: "100000000019",
      bank_account_name: "Fikirte Tesfaye",
      email: "fikirte19@example.com",
      email_2: "fikirte19alt@example.com",
      image_url: "https://example.com/images/fikirte.jpg",
      image_file_id: "img_019",
      document: "https://example.com/docs/fikirte.pdf",
      document_file_id: "doc_019",
      remark: "Engaged member",
      status: "ACTIVE",
    },
    {
      custom_id: "M-0020",
      first_name: "Daniel",
      second_name: "Kebede",
      last_name: "Haile",
      profession: "Software Developer",
      title: "Mr.",
      job_business: "Tech Startup",
      id_number: "ETID1020",
      birth_date: new Date("1992-11-12"),
      citizen: "Ethiopian",
      joined_date: new Date("2021-09-16"),
      wereda: "03",
      zone_or_district: "Addis Ketema",
      kebele: "07",
      sex: "MALE",
      phone_number: "0911778899",
      phone_number_2: "0922778899",
      member_type: "ASSOCIATE",
      bank_name: "CBE",
      bank_account_number: "100000000020",
      bank_account_name: "Daniel Kebede",
      email: "daniel20@example.com",
      email_2: "daniel20alt@example.com",
      image_url: "https://example.com/images/daniel.jpg",
      image_file_id: "img_020",
      document: "https://example.com/docs/daniel.pdf",
      document_file_id: "doc_020",
      remark: "Tech savvy",
      status: "ACTIVE",
    },
    {
      custom_id: "M-0021",
      first_name: "Rahel",
      second_name: "Gebremariam",
      last_name: "Tsegaye",
      profession: "Teacher",
      title: "Mrs.",
      job_business: "Primary School",
      id_number: "ETID1021",
      birth_date: new Date("1987-05-02"),
      citizen: "Ethiopian",
      joined_date: new Date("2018-10-05"),
      wereda: "07",
      zone_or_district: "Lideta",
      kebele: "09",
      sex: "FEMALE",
      phone_number: "0911446677",
      phone_number_2: "0922446677",
      member_type: "REGULAR",
      bank_name: "Nib Bank",
      bank_account_number: "100000000021",
      bank_account_name: "Rahel Gebremariam",
      email: "rahel21@example.com",
      email_2: "rahel21alt@example.com",
      image_url: "https://example.com/images/rahel.jpg",
      image_file_id: "img_021",
      document: "https://example.com/docs/rahel.pdf",
      document_file_id: "doc_021",
      remark: "Experienced educator",
      status: "ACTIVE",
    },
    {
      custom_id: "M-0022",
      first_name: "Kidus",
      second_name: "Tadesse",
      last_name: "Abebe",
      profession: "Driver",
      title: "Mr.",
      job_business: "Logistics",
      id_number: "ETID1022",
      birth_date: new Date("1979-06-06"),
      citizen: "Ethiopian",
      joined_date: new Date("2019-02-20"),
      wereda: "06",
      zone_or_district: "Yeka",
      kebele: "11",
      sex: "MALE",
      phone_number: "0911888999",
      phone_number_2: "0922888999",
      member_type: "SUPPORTING",
      bank_name: "Awash Bank",
      bank_account_number: "100000000022",
      bank_account_name: "Kidus Tadesse",
      email: "kidus22@example.com",
      email_2: "kidus22alt@example.com",
      image_url: "https://example.com/images/kidus.jpg",
      image_file_id: "img_022",
      document: "https://example.com/docs/kidus.pdf",
      document_file_id: "doc_022",
      remark: "Reliable driver",
      status: "ACTIVE",
    },
    {
      custom_id: "M-0023",
      first_name: "Mebrat",
      second_name: "Girma",
      last_name: "Kebede",
      profession: "Pharmacist",
      title: "Ms.",
      job_business: "Hospital",
      id_number: "ETID1023",
      birth_date: new Date("1990-01-17"),
      citizen: "Ethiopian",
      joined_date: new Date("2020-07-12"),
      wereda: "10",
      zone_or_district: "Nifas Silk",
      kebele: "12",
      sex: "FEMALE",
      phone_number: "0911777766",
      phone_number_2: "0922777766",
      member_type: "REGULAR",
      bank_name: "Dashen Bank",
      bank_account_number: "100000000023",
      bank_account_name: "Mebrat Girma",
      email: "mebrat23@example.com",
      email_2: "mebrat23alt@example.com",
      image_url: "https://example.com/images/mebrat.jpg",
      image_file_id: "img_023",
      document: "https://example.com/docs/mebrat.pdf",
      document_file_id: "doc_023",
      remark: "Healthcare professional",
      status: "ACTIVE",
    },
    {
      custom_id: "M-0024",
      first_name: "Amare",
      second_name: "Bekele",
      last_name: "Haile",
      profession: "Businessman",
      title: "Mr.",
      job_business: "Retail",
      id_number: "ETID1024",
      birth_date: new Date("1976-04-25"),
      citizen: "Ethiopian",
      joined_date: new Date("2017-09-20"),
      wereda: "04",
      zone_or_district: "Gulele",
      kebele: "05",
      sex: "MALE",
      phone_number: "0911444555",
      phone_number_2: "0922444555",
      member_type: "SUPPORTING",
      bank_name: "CBE",
      bank_account_number: "100000000024",
      bank_account_name: "Amare Bekele",
      email: "amare24@example.com",
      email_2: "amare24alt@example.com",
      image_url: "https://example.com/images/amare.jpg",
      image_file_id: "img_024",
      document: "https://example.com/docs/amare.pdf",
      document_file_id: "doc_024",
      remark: "Supports market events",
      status: "ACTIVE",
    },
    {
      custom_id: "M-0025",
      first_name: "Tigist",
      second_name: "Mulugeta",
      last_name: "Tesfaye",
      profession: "Social Worker",
      title: "Ms.",
      job_business: "NGO",
      id_number: "ETID1025",
      birth_date: new Date("1985-10-10"),
      citizen: "Ethiopian",
      joined_date: new Date("2019-12-01"),
      wereda: "07",
      zone_or_district: "Lideta",
      kebele: "07",
      sex: "FEMALE",
      phone_number: "0911999888",
      phone_number_2: "0922999888",
      member_type: "REGULAR",
      bank_name: "Nib Bank",
      bank_account_number: "100000000025",
      bank_account_name: "Tigist Mulugeta",
      email: "tigist25@example.com",
      email_2: "tigist25alt@example.com",
      image_url: "https://example.com/images/tigist.jpg",
      image_file_id: "img_025",
      document: "https://example.com/docs/tigist.pdf",
      document_file_id: "doc_025",
      remark: "Community leader",
      status: "ACTIVE",
    },
    {
      custom_id: "M-0026",
      first_name: "Samuel",
      second_name: "Ayele",
      last_name: "Gebremedhin",
      profession: "Driver",
      title: "Mr.",
      job_business: "Transport",
      id_number: "ETID1026",
      birth_date: new Date("1978-03-13"),
      citizen: "Ethiopian",
      joined_date: new Date("2018-06-25"),
      wereda: "05",
      zone_or_district: "Kirkos",
      kebele: "04",
      sex: "MALE",
      phone_number: "0911666655",
      phone_number_2: "0922666655",
      member_type: "SUPPORTING",
      bank_name: "Awash Bank",
      bank_account_number: "100000000026",
      bank_account_name: "Samuel Ayele",
      email: "samuel26@example.com",
      email_2: "samuel26alt@example.com",
      image_url: "https://example.com/images/samuel.jpg",
      image_file_id: "img_026",
      document: "https://example.com/docs/samuel.pdf",
      document_file_id: "doc_026",
      remark: "Excellent driver",
      status: "ACTIVE",
    },
    {
      custom_id: "M-0027",
      first_name: "Eleni",
      second_name: "Tsegaye",
      last_name: "Kebede",
      profession: "Teacher",
      title: "Ms.",
      job_business: "High School",
      id_number: "ETID1027",
      birth_date: new Date("1991-07-02"),
      citizen: "Ethiopian",
      joined_date: new Date("2020-03-18"),
      wereda: "09",
      zone_or_district: "Kolfe Keranio",
      kebele: "06",
      sex: "FEMALE",
      phone_number: "0911777767",
      phone_number_2: "0922777767",
      member_type: "REGULAR",
      bank_name: "CBE",
      bank_account_number: "100000000027",
      bank_account_name: "Eleni Tsegaye",
      email: "eleni27@example.com",
      email_2: "eleni27alt@example.com",
      image_url: "https://example.com/images/eleni.jpg",
      image_file_id: "img_027",
      document: "https://example.com/docs/eleni.pdf",
      document_file_id: "doc_027",
      remark: "Passionate teacher",
      status: "ACTIVE",
    },
    {
      custom_id: "M-0028",
      first_name: "Getu",
      second_name: "Tekle",
      last_name: "Wolde",
      profession: "Electrician",
      title: "Mr.",
      job_business: "Construction",
      id_number: "ETID1028",
      birth_date: new Date("1984-05-05"),
      citizen: "Ethiopian",
      joined_date: new Date("2017-12-22"),
      wereda: "03",
      zone_or_district: "Addis Ketema",
      kebele: "13",
      sex: "MALE",
      phone_number: "0911333322",
      phone_number_2: "0922333322",
      member_type: "SUPPORTING",
      bank_name: "Nib Bank",
      bank_account_number: "100000000028",
      bank_account_name: "Getu Tekle",
      email: "getu28@example.com",
      email_2: "getu28alt@example.com",
      image_url: "https://example.com/images/getu.jpg",
      image_file_id: "img_028",
      document: "https://example.com/docs/getu.pdf",
      document_file_id: "doc_028",
      remark: "Experienced electrician",
      status: "ACTIVE",
    },
    {
      custom_id: "M-0029",
      first_name: "Meron",
      second_name: "Gebre",
      last_name: "Tesfaye",
      profession: "Nurse",
      title: "Mrs.",
      job_business: "Hospital",
      id_number: "ETID1029",
      birth_date: new Date("1986-08-18"),
      citizen: "Ethiopian",
      joined_date: new Date("2019-07-11"),
      wereda: "02",
      zone_or_district: "Arada",
      kebele: "08",
      sex: "FEMALE",
      phone_number: "0911445567",
      phone_number_2: "0922445567",
      member_type: "REGULAR",
      bank_name: "Dashen Bank",
      bank_account_number: "100000000029",
      bank_account_name: "Meron Gebre",
      email: "meron29@example.com",
      email_2: "meron29alt@example.com",
      image_url: "https://example.com/images/meron.jpg",
      image_file_id: "img_029",
      document: "https://example.com/docs/meron.pdf",
      document_file_id: "doc_029",
      remark: "Dedicated nurse",
      status: "ACTIVE",
    },
    {
      custom_id: "M-0030",
      first_name: "Tesfahun",
      second_name: "Tesfaye",
      last_name: "Abraham",
      profession: "Mechanic",
      title: "Mr.",
      job_business: "Auto Repair",
      id_number: "ETID1030",
      birth_date: new Date("1983-02-02"),
      citizen: "Ethiopian",
      joined_date: new Date("2018-04-28"),
      wereda: "01",
      zone_or_district: "Bole",
      kebele: "09",
      sex: "MALE",
      phone_number: "0911665544",
      phone_number_2: "0922665544",
      member_type: "SUPPORTING",
      bank_name: "Awash Bank",
      bank_account_number: "100000000030",
      bank_account_name: "Tesfahun Tesfaye",
      email: "tesfahun30@example.com",
      email_2: "tesfahun30alt@example.com",
      image_url: "https://example.com/images/tesfahun.jpg",
      image_file_id: "img_030",
      document: "https://example.com/docs/tesfahun.pdf",
      document_file_id: "doc_030",
      remark: "Reliable mechanic",
      status: "ACTIVE",
    },
  ];
  await prisma.member.createMany({
    data: moreMembers,
    skipDuplicates: true,
  });
  console.log("Inserted members successfully");
}
seedContributionTypes();
//   .catch((e) => console.error("Seeding failed:", e))
//   .finally(() => prisma.$disconnect());
