import Image from "next/image";
import CurrentTime from "../ui/currentTime";

export default function ReportLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="bg-white p-4 border rounded-md w-full" id="report-content">
      {/* Header */}
      <div className="flex items-center justify-between border-b pb-2 mb-4">
        <div className="flex items-center gap-2">
          <Image src="/edirlogo.jpg" alt="Logo" width={50} height={50} />
          <h1 className="text-xl font-bold">ጀሞ እድር ማህበረሰብ</h1>
        </div>
        <h3 className="text-xl font-semibold">Members Info Table </h3>
        <span className="text-sm text-gray-500">
          <CurrentTime />
        </span>
      </div>
      {/* Content */}
      {children}
      {/* Footer */}
      <div className="border-t pt-2 mt-4 text-center text-xs text-gray-500">
        Generated by Edir Reporting System
      </div>
    </div>
  );
}
