// app/contribute/page.tsx
import Link from "next/link";
import prisma from "@/lib/prisma";
import Image from "next/image";
import { generateContributionSchedulesForAllActiveMembers } from "@/lib/services/generateSchedulesForAllMembers";
import { currentUser } from "@clerk/nextjs/server";
import { redirect } from "next/navigation";

export default async function ContributionPage() {
  const user = await currentUser();

  if (!user) {
   return redirect("/sign-in");
  }

  const role = user.publicMetadata?.role;
  if (role !== "chairman") {
  return  redirect("/dashboard");
  }
  const contributionOptions = await prisma.contributionType.findMany({
    select: {
      id: true,
      name: true,
    },
  });

  await generateContributionSchedulesForAllActiveMembers();
// const dummyMembers = [
//   {
//     custom_id: "EDM-0001",
//     first_name: "Abebe",
//     second_name: "Kebede",
//     last_name: "Teshome",
//     profession: "Teacher",
//     title: "Mr",
//     job_business: "School",
//     id_number: "ID20250001",
//     birth_date: new Date("1980-04-12"),
//     citizen: "Ethiopian",
//     joined_date: new Date("2022-01-15"),
//     wereda: "Wereda 1",
//     zone_or_district: "Addis Ababa",
//     kebele: "Kebele 05",
//     sex: "Male",
//     phone_number: "251911000001",
//     phone_number_2: "251911000002",
//     member_type: "New",
//     bank_name: "Commercial Bank",
//     bank_account_number: "12345678901",
//     bank_account_name: "Abebe K Teshome",
//     email: "abebe.kebede@example.com",
//     email_2: "abebe.kebede2@example.com",
//     image_url: null,
//     image_file_id: null,
//     document: null,
//     document_file_id: null,
//     remark: "Good member",
//     created_at: new Date(),
//     status_updated_at: new Date(),
//     status: "Active",
//   },
//   {
//     custom_id: "EDM-0002",
//     first_name: "Almaz",
//     second_name: "Fikru",
//     last_name: "Berhane",
//     profession: "Nurse",
//     title: "Mrs",
//     job_business: "Hospital",
//     id_number: "ID20250002",
//     birth_date: new Date("1985-07-23"),
//     citizen: "Ethiopian",
//     joined_date: new Date("2021-05-10"),
//     wereda: "Wereda 2",
//     zone_or_district: "Addis Ababa",
//     kebele: "Kebele 07",
//     sex: "Female",
//     phone_number: "251911000003",
//     phone_number_2: "251911000004",
//     member_type: "Existing",
//     bank_name: "Awash Bank",
//     bank_account_number: "23456789012",
//     bank_account_name: "Almaz F Berhane",
//     email: "almaz.fikru@example.com",
//     email_2: "almaz.fikru2@example.com",
//     image_url: null,
//     image_file_id: null,
//     document: null,
//     document_file_id: null,
//     remark: "",
//     created_at: new Date(),
//     status_updated_at: null,
//     status: "Active",
//   },
//   {
//     custom_id: "EDM-0003",
//     first_name: "Mekdes",
//     second_name: "Hailemariam",
//     last_name: "Tadesse",
//     profession: "Engineer",
//     title: "Ms",
//     job_business: "Construction",
//     id_number: "ID20250003",
//     birth_date: new Date("1990-12-15"),
//     citizen: "Ethiopian",
//     joined_date: new Date("2023-03-01"),
//     wereda: "Wereda 3",
//     zone_or_district: "Addis Ababa",
//     kebele: "Kebele 01",
//     sex: "Female",
//     phone_number: "251911000005",
//     phone_number_2: "251911000006",
//     member_type: "New",
//     bank_name: "Dashen Bank",
//     bank_account_number: "34567890123",
//     bank_account_name: "Mekdes H Tadesse",
//     email: "mekdes.hailemariam@example.com",
//     email_2: null,
//     image_url: null,
//     image_file_id: null,
//     document: null,
//     document_file_id: null,
//     remark: "Recently joined",
//     created_at: new Date(),
//     status_updated_at: null,
//     status: "Active",
//   },
//   {
//     custom_id: "EDM-0004",
//     first_name: "Daniel",
//     second_name: "Girma",
//     last_name: "Ayele",
//     profession: "Farmer",
//     title: "Mr",
//     job_business: "Farming",
//     id_number: "ID20250004",
//     birth_date: new Date("1975-02-10"),
//     citizen: "Ethiopian",
//     joined_date: new Date("2020-11-20"),
//     wereda: "Wereda 4",
//     zone_or_district: "Oromia",
//     kebele: "Kebele 09",
//     sex: "Male",
//     phone_number: "251911000007",
//     phone_number_2: "251911000008",
//     member_type: "Existing",
//     bank_name: "Nib International Bank",
//     bank_account_number: "45678901234",
//     bank_account_name: "Daniel G Ayele",
//     email: "daniel.girma@example.com",
//     email_2: null,
//     image_url: null,
//     image_file_id: null,
//     document: null,
//     document_file_id: null,
//     remark: "",
//     created_at: new Date(),
//     status_updated_at: new Date(),
//     status: "Inactive",
//   },
//   {
//     custom_id: "EDM-0005",
//     first_name: "Selam",
//     second_name: "Tadesse",
//     last_name: "Bekele",
//     profession: "Teacher",
//     title: "Mrs",
//     job_business: "School",
//     id_number: "ID20250005",
//     birth_date: new Date("1983-08-19"),
//     citizen: "Ethiopian",
//     joined_date: new Date("2019-06-10"),
//     wereda: "Wereda 5",
//     zone_or_district: "Amhara",
//     kebele: "Kebele 12",
//     sex: "Female",
//     phone_number: "251911000009",
//     phone_number_2: "251911000010",
//     member_type: "Existing",
//     bank_name: "Commercial Bank",
//     bank_account_number: "56789012345",
//     bank_account_name: "Selam T Bekele",
//     email: "selam.tadesse@example.com",
//     email_2: null,
//     image_url: null,
//     image_file_id: null,
//     document: null,
//     document_file_id: null,
//     remark: "Active member",
//     created_at: new Date(),
//     status_updated_at: new Date(),
//     status: "Active",
//   },
//   {
//     custom_id: "EDM-0006",
//     first_name: "Birhanu",
//     second_name: "Mekonnen",
//     last_name: "Tesfaye",
//     profession: "Driver",
//     title: "Mr",
//     job_business: "Logistics",
//     id_number: "ID20250006",
//     birth_date: new Date("1982-05-27"),
//     citizen: "Ethiopian",
//     joined_date: new Date("2018-10-22"),
//     wereda: "Wereda 6",
//     zone_or_district: "Addis Ababa",
//     kebele: "Kebele 15",
//     sex: "Male",
//     phone_number: "251911000011",
//     phone_number_2: "251911000012",
//     member_type: "Existing",
//     bank_name: "Awash Bank",
//     bank_account_number: "67890123456",
//     bank_account_name: "Birhanu M Tesfaye",
//     email: "birhanu.mekonnen@example.com",
//     email_2: null,
//     image_url: null,
//     image_file_id: null,
//     document: null,
//     document_file_id: null,
//     remark: "",
//     created_at: new Date(),
//     status_updated_at: null,
//     status: "Active",
//   },
//   {
//     custom_id: "EDM-0007",
//     first_name: "Mulu",
//     second_name: "Teshome",
//     last_name: "Dawit",
//     profession: "Nurse",
//     title: "Ms",
//     job_business: "Hospital",
//     id_number: "ID20250007",
//     birth_date: new Date("1991-09-05"),
//     citizen: "Ethiopian",
//     joined_date: new Date("2022-08-15"),
//     wereda: "Wereda 7",
//     zone_or_district: "Addis Ababa",
//     kebele: "Kebele 20",
//     sex: "Female",
//     phone_number: "251911000013",
//     phone_number_2: "251911000014",
//     member_type: "New",
//     bank_name: "Dashen Bank",
//     bank_account_number: "78901234567",
//     bank_account_name: "Mulu T Dawit",
//     email: "mulu.teshome@example.com",
//     email_2: null,
//     image_url: null,
//     image_file_id: null,
//     document: null,
//     document_file_id: null,
//     remark: "Newly joined nurse",
//     created_at: new Date(),
//     status_updated_at: null,
//     status: "Active",
//   },
//   {
//     custom_id: "EDM-0008",
//     first_name: "Fitsum",
//     second_name: "Abebe",
//     last_name: "Girma",
//     profession: "Accountant",
//     title: "Mr",
//     job_business: "Finance",
//     id_number: "ID20250008",
//     birth_date: new Date("1978-11-11"),
//     citizen: "Ethiopian",
//     joined_date: new Date("2020-02-17"),
//     wereda: "Wereda 8",
//     zone_or_district: "Addis Ababa",
//     kebele: "Kebele 22",
//     sex: "Male",
//     phone_number: "251911000015",
//     phone_number_2: "251911000016",
//     member_type: "Existing",
//     bank_name: "Commercial Bank",
//     bank_account_number: "89012345678",
//     bank_account_name: "Fitsum A Girma",
//     email: "fitsum.abebe@example.com",
//     email_2: null,
//     image_url: null,
//     image_file_id: null,
//     document: null,
//     document_file_id: null,
//     remark: "",
//     created_at: new Date(),
//     status_updated_at: new Date(),
//     status: "Active",
//   },
//   {
//     custom_id: "EDM-0009",
//     first_name: "Sara",
//     second_name: "Mulugeta",
//     last_name: "Alemu",
//     profession: "Teacher",
//     title: "Mrs",
//     job_business: "School",
//     id_number: "ID20250009",
//     birth_date: new Date("1987-01-02"),
//     citizen: "Ethiopian",
//     joined_date: new Date("2021-09-29"),
//     wereda: "Wereda 9",
//     zone_or_district: "Addis Ababa",
//     kebele: "Kebele 25",
//     sex: "Female",
//     phone_number: "251911000017",
//     phone_number_2: "251911000018",
//     member_type: "New",
//     bank_name: "Awash Bank",
//     bank_account_number: "90123456789",
//     bank_account_name: "Sara M Alemu",
//     email: "sara.mulugeta@example.com",
//     email_2: null,
//     image_url: null,
//     image_file_id: null,
//     document: null,
//     document_file_id: null,
//     remark: "Active teacher",
//     created_at: new Date(),
//     status_updated_at: null,
//     status: "Active",
//   },
//   {
//     custom_id: "EDM-0010",
//     first_name: "Getachew",
//     second_name: "Tesfaye",
//     last_name: "Bikila",
//     profession: "Businessman",
//     title: "Mr",
//     job_business: "Retail",
//     id_number: "ID20250010",
//     birth_date: new Date("1970-06-15"),
//     citizen: "Ethiopian",
//     joined_date: new Date("2018-03-03"),
//     wereda: "Wereda 10",
//     zone_or_district: "Addis Ababa",
//     kebele: "Kebele 30",
//     sex: "Male",
//     phone_number: "251911000019",
//     phone_number_2: "251911000020",
//     member_type: "Existing",
//     bank_name: "Dashen Bank",
//     bank_account_number: "01234567890",
//     bank_account_name: "Getachew T Bikila",
//     email: "getachew.tesfaye@example.com",
//     email_2: null,
//     image_url: null,
//     image_file_id: null,
//     document: null,
//     document_file_id: null,
//     remark: "Long-time business owner",
//     created_at: new Date(),
//     status_updated_at: new Date(),
//     status: "Active",
//   },
//   {
//     custom_id: "EDM-0011",
//     first_name: "Helen",
//     second_name: "Gebremedhin",
//     last_name: "Hailu",
//     profession: "Doctor",
//     title: "Dr",
//     job_business: "Clinic",
//     id_number: "ID20250011",
//     birth_date: new Date("1982-10-20"),
//     citizen: "Ethiopian",
//     joined_date: new Date("2022-04-15"),
//     wereda: "Wereda 11",
//     zone_or_district: "Addis Ababa",
//     kebele: "Kebele 35",
//     sex: "Female",
//     phone_number: "251911000021",
//     phone_number_2: "251911000022",
//     member_type: "New",
//     bank_name: "Commercial Bank",
//     bank_account_number: "11223344556",
//     bank_account_name: "Helen G Hailu",
//     email: "helen.gebremedhin@example.com",
//     email_2: null,
//     image_url: null,
//     image_file_id: null,
//     document: null,
//     document_file_id: null,
//     remark: "Active doctor",
//     created_at: new Date(),
//     status_updated_at: null,
//     status: "Active",
//   },
//   {
//     custom_id: "EDM-0012",
//     first_name: "Yosef",
//     second_name: "Meles",
//     last_name: "Fikadu",
//     profession: "Student",
//     title: null,
//     job_business: null,
//     id_number: "ID20250012",
//     birth_date: new Date("2000-05-05"),
//     citizen: "Ethiopian",
//     joined_date: new Date("2023-01-10"),
//     wereda: "Wereda 12",
//     zone_or_district: "Addis Ababa",
//     kebele: "Kebele 40",
//     sex: "Male",
//     phone_number: "251911000023",
//     phone_number_2: "251911000024",
//     member_type: "New",
//     bank_name: null,
//     bank_account_number: null,
//     bank_account_name: null,
//     email: "yosef.meles@example.com",
//     email_2: null,
//     image_url: null,
//     image_file_id: null,
//     document: null,
//     document_file_id: null,
//     remark: "",
//     created_at: new Date(),
//     status_updated_at: null,
//     status: "Active",
//   },
//   {
//     custom_id: "EDM-0013",
//     first_name: "Biruktawit",
//     second_name: "Degu",
//     last_name: "Haile",
//     profession: "Lawyer",
//     title: "Ms",
//     job_business: "Law Firm",
//     id_number: "ID20250013",
//     birth_date: new Date("1988-03-14"),
//     citizen: "Ethiopian",
//     joined_date: new Date("2020-07-21"),
//     wereda: "Wereda 13",
//     zone_or_district: "Addis Ababa",
//     kebele: "Kebele 45",
//     sex: "Female",
//     phone_number: "251911000025",
//     phone_number_2: "251911000026",
//     member_type: "Existing",
//     bank_name: "Awash Bank",
//     bank_account_number: "22334455667",
//     bank_account_name: "Biruktawit D Haile",
//     email: "biruktawit.degu@example.com",
//     email_2: null,
//     image_url: null,
//     image_file_id: null,
//     document: null,
//     document_file_id: null,
//     remark: "Experienced lawyer",
//     created_at: new Date(),
//     status_updated_at: new Date(),
//     status: "Active",
//   },
//   {
//     custom_id: "EDM-0014",
//     first_name: "Tesfaye",
//     second_name: "Kassa",
//     last_name: "Mulu",
//     profession: "Engineer",
//     title: "Mr",
//     job_business: "Manufacturing",
//     id_number: "ID20250014",
//     birth_date: new Date("1976-06-08"),
//     citizen: "Ethiopian",
//     joined_date: new Date("2017-12-02"),
//     wereda: "Wereda 14",
//     zone_or_district: "Addis Ababa",
//     kebele: "Kebele 50",
//     sex: "Male",
//     phone_number: "251911000027",
//     phone_number_2: "251911000028",
//     member_type: "Existing",
//     bank_name: "Nib International Bank",
//     bank_account_number: "33445566778",
//     bank_account_name: "Tesfaye K Mulu",
//     email: "tesfaye.kassa@example.com",
//     email_2: null,
//     image_url: null,
//     image_file_id: null,
//     document: null,
//     document_file_id: null,
//     remark: "",
//     created_at: new Date(),
//     status_updated_at: new Date(),
//     status: "Active",
//   },
//   {
//     custom_id: "EDM-0015",
//     first_name: "Saba",
//     second_name: "Fikadu",
//     last_name: "Tesfaye",
//     profession: "Teacher",
//     title: "Mrs",
//     job_business: "School",
//     id_number: "ID20250015",
//     birth_date: new Date("1989-11-22"),
//     citizen: "Ethiopian",
//     joined_date: new Date("2021-03-05"),
//     wereda: "Wereda 15",
//     zone_or_district: "Amhara",
//     kebele: "Kebele 55",
//     sex: "Female",
//     phone_number: "251911000029",
//     phone_number_2: "251911000030",
//     member_type: "New",
//     bank_name: "Commercial Bank",
//     bank_account_number: "44556677889",
//     bank_account_name: "Saba F Tesfaye",
//     email: "saba.fikadu@example.com",
//     email_2: null,
//     image_url: null,
//     image_file_id: null,
//     document: null,
//     document_file_id: null,
//     remark: "New teacher",
//     created_at: new Date(),
//     status_updated_at: null,
//     status: "Active",
//   },
//   {
//     custom_id: "EDM-0016",
//     first_name: "Kebede",
//     second_name: "Berhanu",
//     last_name: "Alemu",
//     profession: "Farmer",
//     title: "Mr",
//     job_business: "Farming",
//     id_number: "ID20250016",
//     birth_date: new Date("1973-01-19"),
//     citizen: "Ethiopian",
//     joined_date: new Date("2016-07-14"),
//     wereda: "Wereda 16",
//     zone_or_district: "Oromia",
//     kebele: "Kebele 60",
//     sex: "Male",
//     phone_number: "251911000031",
//     phone_number_2: "251911000032",
//     member_type: "Existing",
//     bank_name: "Awash Bank",
//     bank_account_number: "55667788990",
//     bank_account_name: "Kebede B Alemu",
//     email: "kebede.berhanu@example.com",
//     email_2: null,
//     image_url: null,
//     image_file_id: null,
//     document: null,
//     document_file_id: null,
//     remark: "Experienced farmer",
//     created_at: new Date(),
//     status_updated_at: new Date(),
//     status: "Active",
//   },
//   {
//     custom_id: "EDM-0017",
//     first_name: "Eleni",
//     second_name: "Kebede",
//     last_name: "Fikru",
//     profession: "Nurse",
//     title: "Ms",
//     job_business: "Hospital",
//     id_number: "ID20250017",
//     birth_date: new Date("1986-04-30"),
//     citizen: "Ethiopian",
//     joined_date: new Date("2019-10-08"),
//     wereda: "Wereda 17",
//     zone_or_district: "Addis Ababa",
//     kebele: "Kebele 65",
//     sex: "Female",
//     phone_number: "251911000033",
//     phone_number_2: "251911000034",
//     member_type: "Existing",
//     bank_name: "Dashen Bank",
//     bank_account_number: "66778899001",
//     bank_account_name: "Eleni K Fikru",
//     email: "eleni.kebede@example.com",
//     email_2: null,
//     image_url: null,
//     image_file_id: null,
//     document: null,
//     document_file_id: null,
//     remark: "",
//     created_at: new Date(),
//     status_updated_at: new Date(),
//     status: "Active",
//   },
//   {
//     custom_id: "EDM-0018",
//     first_name: "Yohannes",
//     second_name: "Tesfaye",
//     last_name: "Mamo",
//     profession: "Engineer",
//     title: "Mr",
//     job_business: "Technology",
//     id_number: "ID20250018",
//     birth_date: new Date("1979-12-10"),
//     citizen: "Ethiopian",
//     joined_date: new Date("2017-01-20"),
//     wereda: "Wereda 18",
//     zone_or_district: "Addis Ababa",
//     kebele: "Kebele 70",
//     sex: "Male",
//     phone_number: "251911000035",
//     phone_number_2: "251911000036",
//     member_type: "Existing",
//     bank_name: "Commercial Bank",
//     bank_account_number: "77889900112",
//     bank_account_name: "Yohannes T Mamo",
//     email: "yohannes.tesfaye@example.com",
//     email_2: null,
//     image_url: null,
//     image_file_id: null,
//     document: null,
//     document_file_id: null,
//     remark: "Tech enthusiast",
//     created_at: new Date(),
//     status_updated_at: new Date(),
//     status: "Active",
//   },
//   {
//     custom_id: "EDM-0019",
//     first_name: "Martha",
//     second_name: "Gebre",
//     last_name: "Fanta",
//     profession: "Businesswoman",
//     title: "Mrs",
//     job_business: "Retail",
//     id_number: "ID20250019",
//     birth_date: new Date("1984-03-03"),
//     citizen: "Ethiopian",
//     joined_date: new Date("2021-07-30"),
//     wereda: "Wereda 19",
//     zone_or_district: "Addis Ababa",
//     kebele: "Kebele 75",
//     sex: "Female",
//     phone_number: "251911000037",
//     phone_number_2: "251911000038",
//     member_type: "New",
//     bank_name: "Awash Bank",
//     bank_account_number: "88990011223",
//     bank_account_name: "Martha G Fanta",
//     email: "martha.gebre@example.com",
//     email_2: null,
//     image_url: null,
//     image_file_id: null,
//     document: null,
//     document_file_id: null,
//     remark: "New retail business owner",
//     created_at: new Date(),
//     status_updated_at: null,
//     status: "Active",
//   },
//   {
//     custom_id: "EDM-0020",
//     first_name: "Samuel",
//     second_name: "Tadesse",
//     last_name: "Bekele",
//     profession: "Mechanic",
//     title: "Mr",
//     job_business: "Auto repair",
//     id_number: "ID20250020",
//     birth_date: new Date("1981-09-12"),
//     citizen: "Ethiopian",
//     joined_date: new Date("2016-11-11"),
//     wereda: "Wereda 20",
//     zone_or_district: "Addis Ababa",
//     kebele: "Kebele 80",
//     sex: "Male",
//     phone_number: "251911000039",
//     phone_number_2: "251911000040",
//     member_type: "Existing",
//     bank_name: "Dashen Bank",
//     bank_account_number: "99001122334",
//     bank_account_name: "Samuel T Bekele",
//     email: "samuel.tadesse@example.com",
//     email_2: null,
//     image_url: null,
//     image_file_id: null,
//     document: null,
//     document_file_id: null,
//     remark: "Trusted mechanic",
//     created_at: new Date(),
//     status_updated_at: new Date(),
//     status: "Active",
//   },
// ];

// async function main() {
//   // Import the Sex and MemberType enums from Prisma client
//   const { Sex, MemberType, Status } = await import("@prisma/client");

//   for (const member of dummyMembers) {
//     await prisma.member.create({
//       data: {
//         ...member,
//         sex: member.sex as typeof Sex[keyof typeof Sex],
//         member_type: member.member_type as typeof MemberType[keyof typeof MemberType],
//         status: member.status as typeof Status[keyof typeof Status],
//       },
//     });
//   }
//   console.log("Dummy members inserted.");
// }

// main()
//   .catch((e) => {
//     console.error(e);
//     process.exit(1);
//   })
//   .finally(async () => {
//     await prisma.$disconnect();
//   });
  return (
    <div className="min-h-screen bg-gray-50">
      <main className="container mx-auto px-4 py-12">
        <div className="text-center mb-12">
          <h1 className="text-4xl font-bold text-gray-900 mb-4">
            Make a Contribution
          </h1>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            Your contributions play a vital role in supporting our Edir
            community. Please select a contribution type below to proceed.
          </p>
        </div>

        {contributionOptions.length === 0 ? (
          <div className="text-center text-gray-500 text-lg mt-12">
            No contribution types found. Please{" "}
            <Link href="/configure-setting" className="text-blue-600 underline">
              add contributions
            </Link>{" "}
            to see them listed here.
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {contributionOptions.map((option) => (
              <Link
                key={option.id}
                href={`/contribution/${option.name}`}
                className="bg-white rounded-2xl shadow-md overflow-hidden transition-transform duration-200 hover:shadow-lg hover:-translate-y-1 focus:outline-none focus:ring-2 focus:ring-blue-500"
              >
                <div className="p-6 flex flex-col items-center text-center">
                  <Image
                    src="/contributionIcon.png"
                    height={80}
                    width={80}
                    alt="Contribution Icon"
                    className="mb-4"
                    unoptimized
                  />
                  <h2 className="text-xl font-semibold text-gray-800 mb-1">
                    {option.name}
                  </h2>
                </div>
                <div className="px-6 py-4 bg-gray-100 text-right">
                  <span className="text-blue-600 font-medium group-hover:text-blue-800">
                    Contribute &rarr;
                  </span>
                </div>
              </Link>
            ))}
          </div>
        )}
      </main>
    </div>
  );
}
